### ISSUE TITLE
NAO not updated to explicitly indicate compatibility with NVDA 2024.X

### ISSUE THREAD

**Issue by britechguy** [sharkboyto/nao#48]
It's still in the Add-On Store if you're using 2024.X and check the "Include incompatible add-ons" checkbox.  But based on what a user has said in the NVDA Group in message, [#120693](https://nvda.groups.io/g/nvda/message/120693), it still runs just fine under NVDA 2024.X.

Please update whatever it is that needs updating to make the Add-On Store recognize NAO as being officially compatible with NVDA 2024.X

**Comment by CyrilleB79** [comment]
Or just submit the 2024.1.0 in the Store, since it is already available through external download.
Grazie mille!

**Comment by dreinn** [comment]
yes, we will updated all very soon. thank you.
